{% set name = "django-model-utils" %}
{% set version = "3.1.2" %}
{% set sha256 = "2c057f3bf0859aba27f04389f0cedd2d48f8c9b3848acb86fd9970794e58f477" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - django >=1.8

about:
  home: https://github.com/jazzband/django-model-utils
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Django model mixins and utilities.'
  description: 
    Django model mixins and utilities. django-model-utils supports Django 1.8 through 
    1.10 (latest bugfix release in each series only) on Python 2.7, 3.3 (Django 1.8 only), 3.4 and 3.5.
  doc_url: https://django-model-utils.readthedocs.io/en/latest/
  dev_url: https://github.com/jazzband/django-model-utils

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
