travis:
  secure:
    BINSTAR_TOKEN: XFP6Kisa7+5DZ1VQgLLJogLO55OcZcTHCkAaMjC7y3huYLpmdNjTJJufgbTdxqXHSMrRzdgwFwXHmm3w+srDpkM7t/P42hh1gISAhukkk6p1yiABqRrhRTNHZPL7f5NRNe51hH8SLhP+uySY39dRKbIyQhFXBdtYXqORUdYxDnUg6y6RJDd5Wfk3XaFwNV8gU+UbdVAJjk0wrPCPEk7tNtf43X1F2UnUUxHj/I6MHf2IACMtGbAAtaRsf2kWJoZ/qOW3teYoaWh+/bOF+CcyJi3i15MI7Mq88zGmj2jMXt/i6Aakbhm0Pk5nWcdIWA+NRbLiR2Z2uxrkoY2hdoRJo8op37sz4qJAp5r8SqWqdN/dWP0L66SOS9Hj0uRy1uBygMtAwHT5C5pawkXJgr3tCSOOvlhFbWXvBgYyCzldqwKZFIQcXxDtZxRewi3VzQW09asIaoD9JQth+UJtUN3a+8ohRr773ZkefAU9Vo5UVDhfk5ZG0yul5cOHBk+G2i5EbeZcHFN26ynyp7tuMAZMcJpGIV90/hSu1f7i789tUegyKlUK4gWNaH3IIYfAHVELejG05PxrJKJ3TKn0Zy9rpriTJifQUOg7kFnZrIEnEIi0s/ZfnUMVK8z7XAf46UISUSthv3B8c2637VF+GVGAMUfuhGb8XQZcphH4bXWrj90=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
